#!/usr/sh

echo "LOAD COMMON MODULES"

# GLOBAL
export EDITOR=vim
export SSH_KEY_PATH="~/.ssh/rsa_id"

# PATHS
export PATH=$HOME/bin:/usr/local/bin:$PATH
export PATH=$HOME/.composer/vendor/bin:$PATH

# [[ -s "$HOME/.local/share/marker/marker.sh" ]] && source "$HOME/.local/share/marker/marker.sh"

# THEFUCK
eval "$(thefuck --alias)"

# FZF Configuration
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
# ag -l -g "" | fzf
# export FZF_DEFAULT_COMMAND='ag -l -g ""'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_DEFAULT_OPTS='
--color dark,hl:33,hl+:37,fg+:235,bg+:136,fg+:254
--color info:254,prompt:37,spinner:108,pointer:235,marker:235
'
# --color fg:102,bg:233,hl:65,fg+:15,bg+:234,hl+:108
# --color info:108,prompt:109,spinner:108,pointer:168,marker:168

# CONFIGURATION FILES
# FUNCTIONS / ALIASES
source $HOME/.config/bashscripts/alias_dotdrop.zsh
source $HOME/.config/bashscripts/alias_util.zsh
source $HOME/.config/bashscripts/alias_webapi.zsh
source $HOME/.config/bashscripts/alias_fzf.zsh
